apiVersion: v1
kind: Service
metadata:
  name: hugo-app-rolling-update-svc
  labels:
    app: hugo-app-rolling-update
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hugo-app-rolling-update
