apiVersion: v1
kind: Service
metadata:
  name: iis-app-svc
  labels:
    app: iis-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: iis-app