apiVersion: v1
kind: Service
metadata:
  name: mongodb-linux
  labels:
    app: mongodb-linux
spec:
  type: ClusterIP
  ports:
  - port: 27017
    protocol: TCP
    name: mongo
  selector:
    app: mongodb-linux